# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 03:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('pub_date', models.DateField(verbose_name='\u53d1\u8868\u65e5\u671f')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('dsecription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u6587\u7ae0\u6458\u8981')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u4f5c\u8005\u59d3\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u4f5c\u8005\u90ae\u7bb1')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='\u4f5c\u8005\u5e74\u9f84')),
                ('gender', models.CharField(blank=True, choices=[('man', '\u7537'), ('women', '\u5973')], max_length=2, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='\u624b\u673a')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='\u5730\u5740')),
                ('photo', models.ImageField(blank=True, upload_to='images', verbose_name='\u6587\u4ef6')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myarticle.Author'),
        ),
    ]
