# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', '\u7537'), ('women', '\u5973')], max_length=3, verbose_name='\u6027\u522b'),
        ),
    ]
