# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0003_auto_20180119_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_list',
            old_name='positon',
            new_name='position',
        ),
    ]
