# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0004_auto_20180123_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
