# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0006_userlogin_emai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='emai',
            new_name='email',
        ),
    ]
