# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
